language: rust
sudo: required
cache: cargo
rust:
  - nightly
  - stable
  - beta
addons:
  apt:
    packages:
      - libssl-dev
services:
  - redis-server
script:
  - cargo test --workspace
  - cargo test --no-default-features --features=runtime_async_std
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
