language: rust
rust:
  - nightly
  - stable
  - beta
services:
  - redis-server
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt -- --check
  - cargo test --workspace
  #TODO: Reenable when a solution has been found to the compilation error
  #- cargo test --workspace --no-default-features --features=runtime_async_std
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
