[package]
name = "redis-async"
version = "0.1.0"
authors = ["Bunogi <2bunogi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-preview = "0.3.0-alpha.17"
runtime = "0.3.0-alpha.6"
quick-error = "1.2.2"

[dev-dependencies]
lazy_static = "1.3.0"
num_cpus = "1.10.1"
doc-comment = "0.3.1"