[package]
name = "darkredis"
version = "0.3.1"
authors = ["Bunogi <haakon.jordet@gmail.com>"]
edition = "2018"
publish = false

description = "Async Redis client using std::future"
license = "Zlib"
readme = "README.md"
keywords = ["redis", "async", "database"]
categories = ["database", "web-programming"]
repository = "https://github.com/Bunogi/darkredis"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "0.99.4"
futures-preview = "0.3.0-alpha.18"
quick-error = "1.2.2"

[dev-dependencies]
lazy_static = "1.3.0"
num_cpus = "1.10.1"
runtime = "0.3.0-alpha.7"